modLoader = "javafml"
loaderVersion = "[3,)"
issueTrackerURL = "https://github.com/zziger/obs-overlay/issues"
license = "MIT"

[[mods]]
modId = "obs_overlay"
version = "${version}"
displayName = "OBS Overlay"
authors = "zziger"
description = '''
Hide HUD elements from OBS stream by making them an overlay.
'''
displayTest="IGNORE_ALL_VERSION"
logoFile = "assets/obs_overlay/icon.png"

[[dependencies.obs_overlay]]
modId = "forge"
mandatory = true
versionRange = "[47.4.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.obs_overlay]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.obs_overlay]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.obs_overlay]]
modId = "cloth_config"
mandatory = true
versionRange = "[11.1.136,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "obs_overlay.mixins.json"

[[mixins]]
config = "obs_overlay.neoforge.mixins.json"
