modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/zziger/obs-overlay/issues"
license = "MIT"

[[mods]]
modId = "obs_overlay"
version = "${version}"
displayName = "OBS Overlay"
authors = "zziger"
description = '''
Hide HUD elements from OBS stream by making them an overlay.
'''
displayTest="IGNORE_ALL_VERSION"
logoFile = "assets/obs_overlay/icon.png"

[[dependencies.obs_overlay]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.obs_overlay]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.obs_overlay]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.obs_overlay]]
modId = "cloth_config"
type = "required"
versionRange = "[15.0.127,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "obs_overlay.mixins.json"

[[mixins]]
config = "obs_overlay.neoforge.mixins.json"
