name: Build and Release (1.21)

on:
  push:
    tags:
      - '*.*.*+*.*',
      - '*.*.*+*.*.*'
    branches:
      - "1.21"

jobs:
  build:
    name: "Build and Release"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup and Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --stacktrace --no-daemon

      - name: Setting mod version
        run: |
          cat gradle.properties | grep ^mod_version | sed -e 's/ //g' >> $GITHUB_ENV
          cat gradle.properties | grep ^minecraft_version | sed -e 's/ //g' >> $GITHUB_ENV

      - name: Validate Mod version
        uses: nick-fields/assert-action@v2
        with:
          expected: '${{ github.ref_name }}'
          actual: '${{ env.mod_version }}+${{ env.minecraft_version }}'

      - name: Create package name
        run: echo "package_name=$mod_version - Minecraft $minecraft_version" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ env.package_name }}
          generate_release_notes: true
          files: |
            **/build/libs/
            !build/libs/
            !**/*-dev.jar
            !**/*-shadow.jar
            !**/*-transformProduction*.jar
            !**/testmod*/

#      - name: Release to Maven and CurseForge
#        uses: gradle/gradle-build-action@v2
#        env:
#          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
#          CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
#          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
#        with:
#          arguments: publish publishUnified --stacktrace --no-daemon